name: Bucket_create
on:
  workflow_dispatch:
       inputs :
          aws-region-name:
             description: aws-region
             required: true
 
    
env:
  bucket: pratyank-bucket
  tfstate_file: CV.tfstate
  
  aws-region: ${{github.event.inputs.aws-region-name}}

jobs:
  terraform_plan:
    name: terraform
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.3.4

        
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWSACCESSKEYID}}
          aws-secret-access-key: ${{secrets.AWSSECRETACCESSKEY}}
          aws-session-token: ${{secrets.AWSSESSIONTOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          cd bucket
          terraform init -reconfigure -backend-config="bucket=${{env.bucket}}" -backend-config="key=${{env.tfstate_file}}"
      
      - name: terraform plan
        run: |
          cd bucket
          terraform plan 
      - name: terraform apply  
      
        run: |
          cd bucket
          terraform apply -auto-approve
